[colors]
ansi = [
  'black',
  'maroon',
  'green',
  'olive',
  'navy',
  'purple',
  'teal',
  'silver',
]
brights = [
  'grey',
  'red',
  'lime',
  'yellow',
  'blue',
  'fuchsia',
  'aqua',
  'white',
]
background = '#212337'
compose_cursor = '#f7c67f'
cursor_bg = '#37f499'
cursor_border = '#04d1f9'
cursor_fg = '#212337'
foreground = '#ebfafa'
scrollbar_thumb = '#37f499'
selection_bg = 'rgba(26.666668% 27.843138% 35.294117% 50%)'
selection_fg = 'rgba(0% 0% 0% 0%)'
split = '#a48cf2'

[metadata]
aliases = []
author = 'jacobrreed'
name = 'xldritch'
origin_url = 'https://github.com/eldritch-theme/eldritch/ports/terminal/wezterm'
